kind: pipeline
type: docker
name: release-by-tag

steps:
- name: update-default-branch
  image: casperlabs/node-build-u1804
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - "pip3 install PyGithub semantic_version"
    - "./ci/change_default_branch.py"

volumes:
- name: nctl-temp-dir
  temp: {}

trigger:
  ref:
  - refs/tags/v*
